### ISSUE TITLE
If I want a rectangle, how can I modify it?

### ISSUE THREAD

**Issue by BrentHuang** [krepa098/stl2thumbnail#1]
Your program can only generate square thumbnails. If I want a rectangle, how can I modify it?

**Comment by krepa098** [comment]
Indeed, it is currently limited to square thumbnails. I think it would only require minor changes to support non-square outputs. Have a look at raster/backend.cpp as a starting point.

**Comment by BrentHuang** [comment]
yes, for non-square outputs, I think we should modify this line: 
     auto projection    = glm::ortho(zoom * .5f, -zoom * .5f, -zoom * .5f, zoom * .5f, 0.0f, 1.0f);
but I don't know how to change it. 
Can you help me, I can verify it.

**Comment by BrentHuang** [comment]
please have a look at https://github.com/BrentHuang/stl2thumbnail.git 

thank you very much

**Comment by BrentHuang** [comment]
it's ok now, thank you.

**Comment by BrentHuang** [comment]
it's ok now, thank you.
