### ISSUE TITLE
Ubuntu build fail

### ISSUE THREAD

**Issue by it-fm** [krepa098/stl2thumbnail#3]
I have the following depencia error when compiling on Ubuntu 19

CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: KIO)

**Comment by krepa098** [comment]
It's trying to build the thumbnail generator for KDE. For now just comment `add_subdirectory(generators/kde)` in `CMakeLists.txt`. I'll have to think about a proper solution.
