### ISSUE TITLE
Error during installation : no ECM package configuration found

### ISSUE THREAD

**Issue by Titome** [krepa098/stl2thumbnail#7]
Hi !

Thanks for your work.

I cannot install stl2thumbnail. During this command `cmake -DCMAKE_INSTALL_PREFIX="/usr"` I have this error : 
```
[...]
-- Found PNG: /usr/lib/libpng.so (found version "1.6.37") 
CMake Error at generators/kde/CMakeLists.txt:5 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
[...]
```

Same error when I want to install with AUR package.

I use ArchLinux with KDE.

Thank you for your help.

**Comment by krepa098** [comment]
Hello,

I think you're missing the `extra-cmake-modules` package which is also currently missing from the AUR package. I'll update the pkgbuild. In the meantime you can use the `PKGBUILD` in `dist/linux/archlinux/PKGBUILD`.

Thank you for your feedback

**Comment by Titome** [comment]
Thank you, it's work very well :))

![Screenshot_20200908_122830](https://user-images.githubusercontent.com/748679/92465821-69933200-f1cf-11ea-9247-fabc27e5b448.png)

**Comment by krepa098** [comment]
The AUR PKGBUILD is now updated.
